### ISSUE TITLE
searchd error: client version is higher than daemon version

### ISSUE THREAD

**Issue by msummers** [kpumuk/sphinx#1]
Sphinx::SphinxInternalError: searchd error: client version is higher than daemon version (client is v.1.29, daemon is v.1.25)

Rails 3.2.13, sphinx gem 2.1.1.3212, Sphinx 2.0.6-release (r3473).

Other Sphinx gems indicate a sphinx.yml file, I'm not seeing that with this gem.

How do I ensure that the gem and Sphinx are in-sync?

Thanks.

**Comment by kpumuk** [comment]
If you're using Sphinx < 2.1.1, stick with previous version of the gem (0.9.10.2122). There are no critical changes, just protocol updates (query options, outer selects, etc)
