### ISSUE TITLE
TypeError: can't convert FalseClass into time interval

### ISSUE THREAD

**Issue by fatum** [kpumuk/sphinx#2]
When i run simple example raised error (searchd is running): 

[22] pry(main)> Sphinx::Client.new(Logger.new(STDOUT)).query('test')
[sphinx] version: 1.3.3, [<Sphinx::Server: localhost:9312>]
[sphinx] query('test', '_', ''), <Sphinx::Client: 1 servers, params: {:error=>"", :warning=>"", :connect_error=>false, :servers=>[<Sphinx::Server: localhost:9312>], :connect_timeout=>{:timeout=>0, :retries=>1}, :request_timeout=>{:timeout=>0, :retries=>1}, :retries=>{:count=>0, :delay=>0}, :limits=>{:offset=>0, :limit=>20, :max=>1000, :cutoff=>0}, :max_query_time=>0, :overrides=>[], :select=>"_", :match_mode=>0, :ranking=>{:mode=>0, :expression=>""}, :sort_mode=>{:mode=>0, :sort_by=>""}, :weights=>[], :field_weights=>{}, :index_weights=>[], :id_range=>{:min=>0, :max=>0}, :filters=>[], :geo_anchor=>[], :group_by=>{:attribute=>"", :func=>0, :sort=>"@group desc"}, :group_distinct=>"", :query_flags=>{:bitset=>0, :predicted_time=>0}, :outer_select=>{:has_outer=>false, :sort_by=>"", :offset=>0, :limit=>0}}>
[sphinx] run_queries(1 queries)
[sphinx] search on server localhost:9312
TypeError: can't convert FalseClass into time interval
from /Users/maxfilipovich/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/net/protocol.rb:143:in `select'

I've missed smth?

**Comment by pavlo** [comment]
I'm having the same issue, is there a tip to resolve? Thanks!

**Comment by timtait** [comment]
I got this error when upgrading ruby versions from 1.8.7 to 1.9.3.

Try setting the sphinx gem version to 0.9.10.2122
